modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/dmillerw/Ping/issues"
displayURL="https://minecraft.curseforge.com/projects/ping"
logoFile="logo.png"
credits="Thanks to Wiiv for making the models!"
authors="Girafi, dmillerw"
[[mods]] #mandatory
modId="ping"
version="${version}"
displayName="Ping"
description='''
Inspired by Portal 2, this mod brings the Ping tool into Minecraft.
'''